<?php echo ("EDIT");?>
<div class="container">
	<form method='POST' action="/magento2/blog/index/cussave">
	    <div class="form-group">
	        <label for="name">Name</label>
	        <input type="text" class="form-control" id="name" placeholder="Enter a name" name="name" value="<?php $cus = $block->getPost(); echo $cus->getName(); ?>">
	    </div>

	    <div class="form-group">
	        <label for="phone">Password</label>
	        <input type="text" class="form-control" id="url" placeholder="Enter a phone" name="url" value="<?php if (isset($cus['url_key'])) echo $cus->getPassword();?>">
	    </div>
	    <div class="form-group">
	        <label for="organization">Content</label>
	        <input type="text" class="form-control" id="content" placeholder="Enter a organization" name="content" value="<?php if (isset($cus['content'])) echo $cus->getContent();?>">
	    </div>
	    <div class="form-group">
	        <label for="phone">Status</label>
	        <input type="text" class="form-control" id="status" placeholder="Enter a phone" name="status" value="<?php if (isset($cus['status'])) echo $cus->getStatus();?>">
	    </div>
	    <button type="submit" class="btn btn-primary" name="editbtn" value="<?php if (isset($cus['post_id'])) echo $cus->getId();?>">Submit</button>
	</form>
</div>
